# 3D Array

In [37]:
import numpy as np

arr = np.array([
    [
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]
    ],

    [
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]
    ],

    [
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]
    ]
])

print(arr.shape)

(3, 4, 5)


In [ ]:
# Assignment: 3D Array Indexing & Slicing

# Section A – Access Individual Elements

# Write a statement to extract:

10
24
37
43
54
66
58
49

In [11]:
#Answer:
print(arr[0, 0, 0])
print(arr[0, 2, 4])
print(arr[1, 1, 2])
print(arr[1, 2, 3])
print(arr[2, 0, 4])
print(arr[2, 3, 1])
print(arr[2, 1, 3])
print(arr[1, 3, 4])


10
24
37
43
54
66
58
49


In [ ]:
# Section B – Access Complete Rows

# Write a statement to extract:

1.
[15, 16, 17, 18, 19]

2.
[40, 41, 42, 43, 44]

3.
[65, 66, 67, 68, 69]

In [12]:
#Answer:
print("1.")
print(arr[0,1,:])
print("\n2.")
print(arr[1,2,:])
print("\n3.")
print(arr[2,3,:])

1.
[15 16 17 18 19]

2.
[40 41 42 43 44]

3.
[65 66 67 68 69]


In [ ]:
# Section C – Access Complete 2D Matrices

# Extract:

The first matrix
The second matrix
The third matrix

In [15]:
#Answer:
print("The first matrix")
print(arr[0,:,:])
print("\nThe second matrix")
print(arr[1,:,:])
print("\nThe third matrix")
print(arr[2,:,:])

The first matrix
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

The second matrix
[[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]

The third matrix
[[50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]]


In [ ]:
# Section D – Column Extraction
1
[10, 15, 20, 25]

2
[32, 37, 42, 47]


3
[54, 59, 64, 69]

In [18]:
#Answer:
print("1")
print(arr[0,:,0])
print("\n2")
print(arr[1,:,2])
print("\n3")
print(arr[2,:,4])

1
[10 15 20 25]

2
[32 37 42 47]

3
[54 59 64 69]


In [ ]:
# Section E – Slicing

Extract:

The first two matrices.
The last two matrices.
The first two rows from every matrix.
The last two rows from every matrix.
The first three columns from every matrix.
The last two columns from every matrix.

In [21]:
#Answer:
print("The first two matrices.")
print(arr[0:2,:,:])
print("\nThe last two matrices.")
print(arr[1:3,:,:])
print("\nThe first two rows from every matrix.")
print(arr[:,0:2,:])
print("\nThe last two rows from every matrix.")
print(arr[:,1:3,:])
print("\nThe first three columns from every matrix.")
print(arr[:,:,0:3])
print("\nThe last two columns from every matrix.")
print(arr[:,:,1:3])

The first two matrices.
[[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]

The last two matrices.
[[[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]

The first two rows from every matrix.
[[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[50 51 52 53 54]
  [55 56 57 58 59]]]

The last two rows from every matrix.
[[[15 16 17 18 19]
  [20 21 22 23 24]]

 [[35 36 37 38 39]
  [40 41 42 43 44]]

 [[55 56 57 58 59]
  [60 61 62 63 64]]]

The first three columns from every matrix.
[[[10 11 12]
  [15 16 17]
  [20 21 22]
  [25 26 27]]

 [[30 31 32]
  [35 36 37]
  [40 41 42]
  [45 46 47]]

 [[50 51 52]
  [55 56 57]
  [60 61 62]
  [65 66 67]]]

The last two columns from every matrix.
[[[11 12]
  [16 17]
  [21 22]
  [26 27]]

 [[31 32]
  [36 37]
  [41 42]
  [4

In [ ]:
# Section F – Advanced Slicing

[
 [10, 11, 12],
 [15, 16, 17]
]

In [22]:
print(arr[0,0:2,0:3])

[[10 11 12]
 [15 16 17]]


In [ ]:
[
 [42, 43, 44],
 [47, 48, 49]
]

In [23]:
print(arr[1,2:4,2:5])

[[42 43 44]
 [47 48 49]]


In [ ]:
[
 [55, 56],
 [60, 61],
 [65, 66]
]

In [24]:
print(arr[2,1:4,0:2])

[[55 56]
 [60 61]
 [65 66]]


In [ ]:
[
 [13, 14],
 [18, 19]
]

In [26]:
print(arr[0,0:2,3:])

[[13 14]
 [18 19]]


In [ ]:
# Section G –  Questions

Write a single slicing statement to extract:

Every alternate matrix.
Every alternate row from all matrices.
Every alternate column from all matrices.
The first column from every matrix.
The last column from every matrix.
The middle row from every matrix.
The middle column from every matrix.
Reverse the order of matrices.
Reverse the rows inside every matrix.
Reverse the columns inside every matrix.

In [46]:
#Answer:
print("Every alternate matrix.")
print(arr[::2,:,:])
print("\nEvery alternate row from all matrices.")
print(arr[:,::2,:])
print("\nEvery alternate column from all matrices.")
print(arr[:,:,::2])
print("\nThe first column from every matrix.")
print(arr[:,:,0])
print("\nThe last column from every matrix.")
print(arr[:,:,-1])
print("\nThe middle row from every matrix.")
print(arr[:,arr.shape[1]//2,:])
print("\nThe middle column from every matrix.")
print(arr[:,:,arr.shape[1]//2])
print("\nReverse the order of matrices.")
print(arr[::-1,:,:])
print("\nReverse the rows inside every matrix.")
print(arr[:,::-1,:])
print("\nReverse the columns inside every matrix.")
print(arr[:,:,::-1])

Every alternate matrix.
[[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]

Every alternate row from all matrices.
[[[10 11 12 13 14]
  [20 21 22 23 24]]

 [[30 31 32 33 34]
  [40 41 42 43 44]]

 [[50 51 52 53 54]
  [60 61 62 63 64]]]

Every alternate column from all matrices.
[[[10 12 14]
  [15 17 19]
  [20 22 24]
  [25 27 29]]

 [[30 32 34]
  [35 37 39]
  [40 42 44]
  [45 47 49]]

 [[50 52 54]
  [55 57 59]
  [60 62 64]
  [65 67 69]]]

The first column from every matrix.
[[10 15 20 25]
 [30 35 40 45]
 [50 55 60 65]]

The last column from every matrix.
[[14 19 24 29]
 [34 39 44 49]
 [54 59 64 69]]

The middle row from every matrix.
[[20 21 22 23 24]
 [40 41 42 43 44]
 [60 61 62 63 64]]

The middle column from every matrix.
[[12 17 22 27]
 [32 37 42 47]
 [52 57 62 67]]

Reverse the order of matrices.
[[[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]

 [[30 

# 2D ARRAY

In [47]:
import numpy as np

arr = np.array([
    [10, 11, 12, 13, 14, 15],
    [20, 21, 22, 23, 24, 25],
    [30, 31, 32, 33, 34, 35],
    [40, 41, 42, 43, 44, 45],
    [50, 51, 52, 53, 54, 55],
    [60, 61, 62, 63, 64, 65]
])

print(arr.shape)

(6, 6)


In [ ]:
# 2D Array Indexing & Slicing

Extract the following using a single indexing/slicing statement
1. Every alternate row

Expected Output:

[
 [10,11,12,13,14,15],
 [30,31,32,33,34,35],
 [50,51,52,53,54,55]
]

In [50]:
#Answer:
print(arr[::2,:])

[[10 11 12 13 14 15]
 [30 31 32 33 34 35]
 [50 51 52 53 54 55]]


In [ ]:
# 2. Every alternate column

Expected Output:

[
 [10,12,14],
 [20,22,24],
 [30,32,34],
 [40,42,44],
 [50,52,54],
 [60,62,64]
]


In [51]:
#Answer:
print(arr[:,::2])

[[10 12 14]
 [20 22 24]
 [30 32 34]
 [40 42 44]
 [50 52 54]
 [60 62 64]]


In [ ]:
3. First column

Expected Output:

[10,20,30,40,50,60]

In [52]:
#Answer:
print(arr[:,0])

[10 20 30 40 50 60]


In [ ]:
4. Last column

Expected Output:

[15,25,35,45,55,65]

In [53]:
#Answer:
print(arr[:,-1])

[15 25 35 45 55 65]


In [ ]:
5. Middle row

Expected Output:

[40,41,42,43,44,45]

In [55]:
#Answer:
print(arr[arr.shape[0]//2,:])

[40 41 42 43 44 45]


In [ ]:
6. Middle column

Expected Output:

[13,23,33,43,53,63]

In [56]:
#Answer:
print(arr[:,arr.shape[1]//2])

[13 23 33 43 53 63]


In [ ]:
7. First three rows

Expected Output:

[
 [10,11,12,13,14,15],
 [20,21,22,23,24,25],
 [30,31,32,33,34,35]
]


In [57]:
#Answer:
print(arr[0:3,:])

[[10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]]


In [ ]:
8. Last three rows

Expected Output:

[
 [40,41,42,43,44,45],
 [50,51,52,53,54,55],
 [60,61,62,63,64,65]
]


In [64]:
#Answer:
print(arr[-3:,:])

[[40 41 42 43 44 45]
 [50 51 52 53 54 55]
 [60 61 62 63 64 65]]


In [ ]:
9. First three columns

Expected Output:

[
 [10,11,12],
 [20,21,22],
 [30,31,32],
 [40,41,42],
 [50,51,52],
 [60,61,62]
]



In [65]:
#Answer:
print(arr[:,0:3])

[[10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]
 [50 51 52]
 [60 61 62]]


In [ ]:
10. Last three columns

Expected Output:

[
 [13,14,15],
 [23,24,25],
 [33,34,35],
 [43,44,45],
 [53,54,55],
 [63,64,65]
]

In [66]:
#Answer:
print(arr[:,-3:])

[[13 14 15]
 [23 24 25]
 [33 34 35]
 [43 44 45]
 [53 54 55]
 [63 64 65]]


In [ ]:
11. Reverse all rows

Expected Output:

[
 [60,61,62,63,64,65],
 [50,51,52,53,54,55],
 [40,41,42,43,44,45],
 [30,31,32,33,34,35],
 [20,21,22,23,24,25],
 [10,11,12,13,14,15]
]


In [67]:
#Answer:
print(arr[::-1,:])

[[60 61 62 63 64 65]
 [50 51 52 53 54 55]
 [40 41 42 43 44 45]
 [30 31 32 33 34 35]
 [20 21 22 23 24 25]
 [10 11 12 13 14 15]]


In [ ]:
12. Reverse all columns

Expected Output:

[
 [15,14,13,12,11,10],
 [25,24,23,22,21,20],
 [35,34,33,32,31,30],
 [45,44,43,42,41,40],
 [55,54,53,52,51,50],
 [65,64,63,62,61,60]
]

In [68]:
#Answer:
print(arr[:,::-1])

[[15 14 13 12 11 10]
 [25 24 23 22 21 20]
 [35 34 33 32 31 30]
 [45 44 43 42 41 40]
 [55 54 53 52 51 50]
 [65 64 63 62 61 60]]


In [ ]:
13. Reverse rows and columns simultaneously

Expected Output:


[
 [65,64,63,62,61,60],
 [55,54,53,52,51,50],
 [45,44,43,42,41,40],
 [35,34,33,32,31,30],
 [25,24,23,22,21,20],
 [15,14,13,12,11,10]
]

In [69]:
#Answer:
print(arr[::-1,::-1])

[[65 64 63 62 61 60]
 [55 54 53 52 51 50]
 [45 44 43 42 41 40]
 [35 34 33 32 31 30]
 [25 24 23 22 21 20]
 [15 14 13 12 11 10]]


# Write a single indexing/slicing statement to extract:


In [ ]:

[
 [22,23,24],
 [32,33,34],
 [42,43,44]
]

In [70]:
#Answer:
print(arr[1:4,2:5])

[[22 23 24]
 [32 33 34]
 [42 43 44]]


In [ ]:
[
 [11,13,15],
 [31,33,35],
 [51,53,55]
]


In [71]:
#Answer:
print(arr[0::2,1::2])

[[11 13 15]
 [31 33 35]
 [51 53 55]]


In [ ]:
[
 [40,41,42,43,44,45],
 [50,51,52,53,54,55]
]


In [72]:
#Answer:
print(arr[3:5,:])

[[40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [ ]:
[
 [14,15],
 [24,25],
 [34,35],
 [44,45],
 [54,55],
 [64,65]
]

In [73]:
#Answer:
print(arr[:,-2:])

[[14 15]
 [24 25]
 [34 35]
 [44 45]
 [54 55]
 [64 65]]
