# Python Assignment
Topic: 3D Arrays and Dictionaries


# Part A – 3D Arrays  

# Question 1  
## Create the following 3D array.

Layer 1

[1, 2, 3]
[4, 5, 6]

Layer 2

[7, 8, 9]
[10, 11, 12]

In [ ]:
Write a Python program to:

Print the complete 3D array.
Print the first layer.
Print the second row of the second layer.
Print the element 11.

In [1]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

# Question 2  

Using the same 3D array, reverse the order of layers.

Expected Output

Layer 2

[7, 8, 9]
[10,11,12]

Layer 1

[1,2,3]
[4,5,6]

In [2]:
arr[::-1,::,::]

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

# Question 3  

##  Reverse every row inside every layer.

Expected Output

In [3]:
arr[::,::-1,::]

array([[[ 4,  5,  6],
        [ 1,  2,  3]],

       [[10, 11, 12],
        [ 7,  8,  9]]])

# Question 4  

Completely reverse the entire 3D array by reversing:

    the order of layers,
    the order of rows inside each layer,
    the elements inside every row.

Expected Output

[12,11,10]
[9,8,7]
[6,5,4]
[3,2,1]

In [4]:
arr[::-1,::-1,::-1]

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

# Part B – Dictionaries

In [ ]:
# Create a dictionary to store the following student details.

| Key        | Value   |
| ---------- | ------- |
| Roll No    | 101     |
| Name       | Alice   |
| Age        | 20      |
| Department | AI & DS |
| CGPA       | 8.9     |

Display all the information. (use print)

In [7]:
a = {"Roll No":101, "Name": "Alice", "Age": 20, "Department":"AI & DS", "CGPA":8.9}

In [ ]:
# Question 6  

Using the dictionary created above,

    Update the CGPA to 9.2
    Add a new key named City with value Chennai
    Display the updated dictionary.

In [11]:
a["CGPA"] = 9.2
a["City"] = "Chennai"
print(a)

{'Roll No': 101, 'Name': 'Alice', 'Age': 20, 'Department': 'AI & DS', 'CGPA': 9.2, 'City': 'Chennai'}


In [ ]:
# Question 7  

Write a program to print

    all keys
    all values
    all key-value pairs

using appropriate dictionary methods.

In [17]:
print(a.keys())
print(a.values())
print(a.items())

dict_keys(['Roll No', 'Name', 'Age', 'Department', 'CGPA', 'City'])
dict_values([101, 'Alice', 20, 'AI & DS', 9.2, 'Chennai'])
dict_items([('Roll No', 101), ('Name', 'Alice'), ('Age', 20), ('Department', 'AI & DS'), ('CGPA', 9.2), ('City', 'Chennai')])


In [ ]:
# Question 8  

Create the following nested dictionary.

students = {
    "Student1": {
        "Name": "John",
        "Age": 22
    },
    "Student2": {
        "Name": "Alice",
        "Age": 21
    },
    "Student3": {
        "Name": "David",
        "Age": 20
    }
}

Write a program to

    Print the name of Student2.
    Print the age of Student3.
    Display all student names using a loop.

In [30]:
students = dict(Student1=dict(Name="John",Age=22),Student2=dict(Name="Alice",Age=21),Student3=dict(Name="David",Age=20))
print(f'The name of Student2 is: {students["Student2"]["Name"]}')
print(f'The age of Student3 is: {students["Student3"]["Age"]}')
for student, details in students.items():
    for key,value in details.items():
        if key == "Name":
            print(value)

The name of Student2 is: Alice
The age of Student3 is: 20
John
Alice
David


In [ ]:
# Question 9  

Create a dictionary of five products.

Example

    Laptop
    Mouse
    Keyboard
    Monitor
    Printer

Each product should contain

    Product Name
    Price
    Quantity

Write a program to

    Display all products.
    Print the product with the highest price.
    Calculate the total inventory value

(Formula:  Inventory Value = Price × Quantity)

In [42]:
products = {"Laptop":{"ProductName":"Dell", "Price":23000, "Quantity":5}, "Mouse":{"ProductName":"Lenovo", "Price":249, "Quantity":3}, "Keyboard": {"ProductName":"Zebronics", "Price":452, "Quantity":8}, "Monitor":{"ProductName":"Apple", "Price":9990, "Quantity":4}, "Printer":{"ProductName":"hp", "Price":34570, "Quantity":7}}

print(products)

#Highest Price
highestPrice = 0
for product,details in products.items():
    for key,value in details.items():
        if key == "Price" and value > highestPrice:
            highestPrice = value

for product,details in products.items():
    for key,value in details.items():
        if key == "Price" and value == highestPrice:
            print(f"\nProduct with highest price is: {product}")

#Inventory Value
sum = 0
for product,details in products.items():
    sum = sum + details["Price"] * details["Quantity"]
print(f"\nTotal inventory value is: {sum}")
            

{'Laptop': {'ProductName': 'Dell', 'Price': 23000, 'Quantity': 5}, 'Mouse': {'ProductName': 'Lenovo', 'Price': 249, 'Quantity': 3}, 'Keyboard': {'ProductName': 'Zebronics', 'Price': 452, 'Quantity': 8}, 'Monitor': {'ProductName': 'Apple', 'Price': 9990, 'Quantity': 4}, 'Printer': {'ProductName': 'hp', 'Price': 34570, 'Quantity': 7}}

Product with highest price is: Printer

Total inventory value is: 401313


In [ ]:
# Question 10

Create a dictionary of five students and their marks.

Example

    Alice : 85
    Bob : 92
    Charlie : 78
    David : 88
    Emma : 95

Write a Python program to

    Find the student with the highest marks.
    Find the student with the lowest marks.
    Calculate the average marks.
    Display students who scored more than 85.

In [53]:
students = {"Alice": 85, "Bob": 92, "Charlie": 78, "David": 88, "Emma": 95}

#HighestMarks
highestMark = 0
for mark in students.values():
    if mark > highestMark:
        highestMark = mark

print(highestMark)
for key,val in students.items():
    if val == highestMark:
        print(f"{key} has the highest mark")

#LowestMark
lowestMark = 100
for mark in students.values():
    if mark < lowestMark:
        lowestMark = mark

for key,val in students.items():
    if val == lowestMark:
        print(f"{key} has the lowest mark")

#AverageMarks
sum = 0
for mark in students.values():
    sum = sum + mark
avg = sum / len(students)
print(f"The average is: {avg}")

#More than 85
for name,mark in students.items():
    if mark > 85:
        print(f"{name} has scored more than 85")


95
Emma has the highest mark
Charlie has the lowest mark
The average is: 87.6
Bob has scored more than 85
David has scored more than 85
Emma has scored more than 85
